### ISSUE TITLE
Text not visible

### ISSUE THREAD

**Issue by merlinuwe** [Lemon695/obsidian-recently-added-files#1]
Thanks for your great plugin.

On android 11 I don't see the text:

![Screenshot_2024-11-25-23-24-53-134_md obsidian](https://github.com/user-attachments/assets/610f0985-2a35-45f6-98da-5e38833abed9)

**Comment by Lemon695** [comment]
> 感谢您的出色插件。
> 
> 在android 11上,我看不到文本:
> 
> ![Screenshot_2024-11-25-23-24-53-134_md黑曜石](https://private-user-images.githubusercontent.com/4138869/389722106-610f0985-2a35-45f6-98da-5e38833abed9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzMyNTcsIm5iZiI6MTczMjY3Mjk1NywicGF0aCI6Ii80MTM4ODY5LzM4OTcyMjEwNi02MTBmMDk4NS0yYTM1LTQ1ZjYtOThkYS01ZTM4ODMzYWJlZDkuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjdUMDIwMjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDAxZmQ4YjAxMWY2Zjc2YTM4YTFhZDhiYzAyYTgzMzgyNzJmNDM0YzdkN2FkYzU5ZDM5NDQ4MGMxMDY5Mzg4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Ui2SZhyVFV899hqJvYujMDn2tiLIeUDTBQ7hzmC-G7A)

Thank you for using it. I have been testing it with my Mac and iPhone before, and I don't have an Android phone. Please wait for two days, I will find an Android phone to install Obsidian and test it. Thank you for reminding me.

**Comment by Lemon695** [comment]
> Thanks for your great plugin.
> 
> On android 11 I don't see the text:
> 
> ![Screenshot_2024-11-25-23-24-53-134_md obsidian](https://private-user-images.githubusercontent.com/4138869/389722106-610f0985-2a35-45f6-98da-5e38833abed9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5OTgzNjAsIm5iZiI6MTczMzk5ODA2MCwicGF0aCI6Ii80MTM4ODY5LzM4OTcyMjEwNi02MTBmMDk4NS0yYTM1LTQ1ZjYtOThkYS01ZTM4ODMzYWJlZDkuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTJUMTAwNzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGM3MzQ3OTlhOGQ1MmUzMTNmODE5YTQyNDA1ZmMyNTQ0N2I1YjU3YTU1M2Q0YjU1NmQ1NjFlZjJhOWIyZmQzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ai_wAWpdfdoiv4Iaa_f5NmxoF1cOpU6NcOzY7LBa6wg)

@merlinuwe  I fixed this issue in version 1.0.8.
